version : 2.1
jobs:
  run_tests:
    docker:
      - image:circleci/norde:14
      steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
